"""add board, inventory, kvti, lecture, product, timetable, visa model and update post extra_data

Revision ID: ab5f37c9eb08
Revises: aa20190d4c8f
Create Date: 2026-03-09 01:44:20.316857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab5f37c9eb08'
down_revision = 'aa20190d4c8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('attribute_schema', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kvtis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timetables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('custom_name', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('visa_type', sa.String(length=50), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('document_url', sa.String(length=255), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('name_ko', sa.String(length=100), nullable=True),
    sa.Column('name_en', sa.String(length=100), nullable=True),
    sa.Column('professor_ko', sa.String(length=50), nullable=True),
    sa.Column('professor_en', sa.String(length=50), nullable=True),
    sa.Column('room_ko', sa.String(length=50), nullable=True),
    sa.Column('room_en', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lecture_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lecture_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Enum('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN', '_text_map', name='dayofweek'), nullable=False),
    sa.Column('start_period', sa.Integer(), nullable=False),
    sa.Column('end_period', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lecture_id'], ['lectures.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('flag_image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('board_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('extra_data', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('likes_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dislikes_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('views_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('popularity_score', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'boards', ['board_id'], ['id'])
        batch_op.drop_column('nickname')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('is_nickname_anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('sex', sa.Enum('MALE', 'FEMALE', 'OTHER', name='sextype'), nullable=False))
        batch_op.add_column(sa.Column('is_sex_anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_country_anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_school_anonymous', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('is_advertisement_agreed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('current_exp', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('current_language', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint(None, ['nickname'])
        batch_op.drop_column('is_visa')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_visa', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('current_language')
        batch_op.drop_column('current_exp')
        batch_op.drop_column('level')
        batch_op.drop_column('is_advertisement_agreed')
        batch_op.drop_column('profile_image_url')
        batch_op.drop_column('is_school_anonymous')
        batch_op.drop_column('is_country_anonymous')
        batch_op.drop_column('is_sex_anonymous')
        batch_op.drop_column('sex')
        batch_op.drop_column('is_nickname_anonymous')
        batch_op.drop_column('nickname')

    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('popularity_score')
        batch_op.drop_column('views_count')
        batch_op.drop_column('dislikes_count')
        batch_op.drop_column('likes_count')
        batch_op.drop_column('extra_data')
        batch_op.drop_column('board_id')

    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_column('flag_image_url')

    op.drop_table('lecture_times')
    op.drop_table('lectures')
    op.drop_table('visas')
    op.drop_table('timetables')
    op.drop_table('kvtis')
    op.drop_table('inventories')
    op.drop_table('products')
    op.drop_table('boards')
    # ### end Alembic commands ###
